GAME_DATA = [
    {"celebrity": "Selena Gomez", "description": "Singer, Actress, Producer", "followers": 200000000},
    {"celebrity": "Cristiano Ronaldo", "description": "Professional Footballer", "followers": 300000000},
    {"celebrity": "Dwayne Johnson", "description": "Actor, Wrestler, Producer", "followers": 250000000},
    {"celebrity": "Kylie Jenner", "description": "Businesswoman, Reality TV Star", "followers": 240000000},
    {"celebrity": "Ariana Grande", "description": "Singer, Actress", "followers": 270000000},
    {"celebrity": "Lionel Messi", "description": "Professional Footballer", "followers": 210000000},
    {"celebrity": "Kim Kardashian", "description": "Businesswoman, Reality TV Star", "followers": 240000000},
    {"celebrity": "Beyoncé", "description": "Singer, Actress", "followers": 180000000},
    {"celebrity": "Justin Bieber", "description": "Singer", "followers": 180000000},
    {"celebrity": "Neymar Jr.", "description": "Professional Footballer", "followers": 170000000},
    {"celebrity": "Taylor Swift", "description": "Singer, Songwriter", "followers": 160000000},
    {"celebrity": "Kendall Jenner", "description": "Model, Reality TV Star", "followers": 170000000},
    {"celebrity": "Jennifer Lopez", "description": "Singer, Actress, Dancer", "followers": 160000000},
    {"celebrity": "LeBron James", "description": "Professional Basketball Player", "followers": 110000000},
    {"celebrity": "Cristiano Ronaldo", "description": "Professional Footballer", "followers": 300000000},
    {"celebrity": "Billie Eilish", "description": "Singer, Songwriter", "followers": 90000000},
    {"celebrity": "Shakira", "description": "Singer, Songwriter", "followers": 70000000},
    {"celebrity": "Ellen DeGeneres", "description": "Comedian, TV Host", "followers": 100000000},
    {"celebrity": "Drake", "description": "Rapper, Singer", "followers": 110000000},
    {"celebrity": "Rihanna", "description": "Singer, Businesswoman", "followers": 140000000},
    {"celebrity": "Kevin Hart", "description": "Comedian, Actor", "followers": 100000000},
    {"celebrity": "Gal Gadot", "description": "Actress", "followers": 40000000},
    {"celebrity": "Chris Hemsworth", "description": "Actor", "followers": 55000000},
    {"celebrity": "Emma Watson", "description": "Actress", "followers": 60000000},
    {"celebrity": "Will Smith", "description": "Actor", "followers": 60000000},
    {"celebrity": "Snoop Dogg", "description": "Rapper, Actor", "followers": 50000000},
    {"celebrity": "Gigi Hadid", "description": "Model", "followers": 68000000},
    {"celebrity": "Zendaya", "description": "Actress, Singer", "followers": 80000000},
    {"celebrity": "David Beckham", "description": "Former Footballer", "followers": 70000000},
    {"celebrity": "Oprah Winfrey", "description": "TV Host, Producer", "followers": 21000000},
    {"celebrity": "Serena Williams", "description": "Tennis Player", "followers": 12000000},
    {"celebrity": "Stephen Curry", "description": "Professional Basketball Player", "followers": 30000000},
    {"celebrity": "Miley Cyrus", "description": "Singer, Actress", "followers": 160000000},
    {"celebrity": "Jessica Alba", "description": "Actress, Businesswoman", "followers": 20000000},
    {"celebrity": "Tiger Woods", "description": "Professional Golfer", "followers": 6000000},
    {"celebrity": "Kanye West", "description": "Rapper, Producer", "followers": 50000000},
    {"celebrity": "Nicki Minaj", "description": "Rapper, Singer", "followers": 160000000},
    {"celebrity": "Lady Gaga", "description": "Singer, Actress", "followers": 130000000},
    {"celebrity": "PewDiePie", "description": "YouTuber", "followers": 120000000},
    {"celebrity": "The Rock", "description": "Actor, Wrestler, Producer", "followers": 250000000},
    {"celebrity": "Jennifer Aniston", "description": "Actress", "followers": 38000000},
    {"celebrity": "Robert Downey Jr.", "description": "Actor", "followers": 50000000},
    {"celebrity": "Tom Hanks", "description": "Actor", "followers": 12000000},
    {"celebrity": "Scarlett Johansson", "description": "Actress", "followers": 50000000},
    {"celebrity": "Brad Pitt", "description": "Actor", "followers": 10000000},
    {"celebrity": "Halle Berry", "description": "Actress", "followers": 8000000},
    {"celebrity": "Daniel Radcliffe", "description": "Actor", "followers": 2000000},
    {"celebrity": "Johnny Depp", "description": "Actor", "followers": 10000000},
    {"celebrity": "Angelina Jolie", "description": "Actress", "followers": 30000000},
    {"celebrity": "George Clooney", "description": "Actor", "followers": 12000000},
    {"celebrity": "Matt Damon", "description": "Actor", "followers": 3000000},
    {"celebrity": "Julia Roberts", "description": "Actress", "followers": 10000000},
    {"celebrity": "Nicole Kidman", "description": "Actress", "followers": 8000000},
    {"celebrity": "Tom Cruise", "description": "Actor", "followers": 6000000},
    {"celebrity": "Eminem", "description": "Rapper", "followers": 70000000},
    {"celebrity": "Adele", "description": "Singer", "followers": 40000000},
    {"celebrity": "Amy Schumer", "description": "Comedian, Actress", "followers": 8000000},
    {"celebrity": "Sandra Bullock", "description": "Actress", "followers": 6000000},
    {"celebrity": "Kate Winslet", "description": "Actress", "followers": 7000000},
    {"celebrity": "Julianne Moore", "description": "Actress", "followers": 3000000},
    {"celebrity": "Jennifer Lawrence", "description": "Actress", "followers": 7000000},
    {"celebrity": "Emma Stone", "description": "Actress", "followers": 12000000},
    {"celebrity": "Cate Blanchett", "description": "Actress", "followers": 3000000},
    {"celebrity": "Charlize Theron", "description": "Actress", "followers": 8000000},
    {"celebrity": "Leonardo DiCaprio", "description": "Actor", "followers": 4000000},
    {"celebrity": "Meryl Streep", "description": "Actress", "followers": 6000000},
    {"celebrity": "Christian Bale", "description": "Actor", "followers": 5000000},
    {"celebrity": "Denzel Washington", "description": "Actor", "followers": 4000000},
    {"celebrity": "Idris Elba", "description": "Actor", "followers": 8000000},
    {"celebrity": "Harrison Ford", "description": "Actor", "followers": 5000000},
    {"celebrity": "Keanu Reeves", "description": "Actor", "followers": 10000000},
    {"celebrity": "Samuel L. Jackson", "description": "Actor", "followers": 7000000},
    {"celebrity": "Mark Wahlberg", "description": "Actor", "followers": 2000000},
    {"celebrity": "Robert Pattinson", "description": "Actor", "followers": 4000000},
    {"celebrity": "Emma Roberts", "description": "Actress", "followers": 5000000},
    {"celebrity": "Anne Hathaway", "description": "Actress", "followers": 6000000},
    {"celebrity": "Rami Malek", "description": "Actor", "followers": 3000000},
    {"celebrity": "Zoe Saldana", "description": "Actress", "followers": 5000000},
    {"celebrity": "Sofia Vergara", "description": "Actress", "followers": 30000000},
    {"celebrity": "Joaquin Phoenix", "description": "Actor", "followers": 5000000},
    {"celebrity": "Jodie Foster", "description": "Actress", "followers": 3000000},
    {"celebrity": "Melissa McCarthy", "description": "Actress", "followers": 3000000},
    {"celebrity": "Hilary Swank", "description": "Actress", "followers": 2000000},
    {"celebrity": "Michelle Pfeiffer", "description": "Actress", "followers": 3000000},
    {"celebrity": "Gwyneth Paltrow", "description": "Actress", "followers": 8000000},
    {"celebrity": "Naomi Watts", "description": "Actress", "followers": 4000000},
    {"celebrity": "Jessica Chastain", "description": "Actress", "followers": 2000000},
    {"celebrity": "Emily Blunt", "description": "Actress", "followers": 7000000},
    {"celebrity": "Reese Witherspoon", "description": "Actress", "followers": 2000000},
    {"celebrity": "Alicia Vikander", "description": "Actress", "followers": 4000000},
    {"celebrity": "Dakota Johnson", "description": "Actress", "followers": 4000000},
    {"celebrity": "Margot Robbie", "description": "Actress", "followers": 3000000},
    {"celebrity": "Emma Thompson", "description": "Actress", "followers": 2000000},
    {"celebrity": "Rihanna", "description": "Singer, Businesswoman", "followers": 140000000},
    {"celebrity": "Jennifer Lawrence", "description": "Actress", "followers": 7000000},
    {"celebrity": "Emma Stone", "description": "Actress", "followers": 12000000},
    {"celebrity": "Cate Blanchett", "description": "Actress", "followers": 3000000},
    {"celebrity": "Charlize Theron", "description": "Actress", "followers": 8000000},
    {"celebrity": "Leonardo DiCaprio", "description": "Actor", "followers": 4000000},
    {"celebrity": "Meryl Streep", "description": "Actress", "followers": 6000000},
    {"celebrity": "Christian Bale", "description": "Actor", "followers": 5000000},
    {"celebrity": "Denzel Washington", "description": "Actor", "followers": 4000000},
    {"celebrity": "Idris Elba", "description": "Actor", "followers": 8000000},
    {"celebrity": "Harrison Ford", "description": "Actor", "followers": 5000000},
    {"celebrity": "Keanu Reeves", "description": "Actor", "followers": 10000000},
    {"celebrity": "Samuel L. Jackson", "description": "Actor", "followers": 7000000},
    {"celebrity": "Mark Wahlberg", "description": "Actor", "followers": 2000000},
    {"celebrity": "Robert Pattinson", "description": "Actor", "followers": 4000000},
    {"celebrity": "Emma Roberts", "description": "Actress", "followers": 5000000},
    {"celebrity": "Anne Hathaway", "description": "Actress", "followers": 6000000},
    {"celebrity": "Rami Malek", "description": "Actor", "followers": 3000000},
    {"celebrity": "Zoe Saldana", "description": "Actress", "followers": 5000000},
    {"celebrity": "Sofia Vergara", "description": "Actress", "followers": 30000000}
]






# GAME_DATA_Reverve = [
#     {"word": "Technology", "description": "The study and development of tools, machines, and systems.", "searches": 550000},
#     {"word": "Science", "description": "The systematic study of the structure and behavior of the physical and natural world.", "searches": 500000},
#     {"word": "Art", "description": "Expression or application of human creative skill and imagination.", "searches": 450000},
#     {"word": "Health", "description": "State of being free from illness or injury; overall well-being.", "searches": 400000},
#     {"word": "Education", "description": "The process of receiving or giving systematic instruction.", "searches": 400000},
#     {"word": "History", "description": "Study of past events, particularly in human affairs.", "searches": 350000},
#     {"word": "Environment", "description": "The surroundings or conditions in which a person, animal, or plant lives.", "searches": 350000},
#     {"word": "Culture", "description": "The customs, arts, social institutions, and achievements of a particular nation or people.", "searches": 400000},
#     {"word": "Food", "description": "Any nutritious substance that people or animals eat or drink.", "searches": 600000},
#     {"word": "Business", "description": "Activities involved in the trade of goods or services.", "searches": 550000},
#     {"word": "Politics", "description": "Activities associated with governance and decision-making within a group or organization.", "searches": 450000},
#     {"word": "Music", "description": "Art form and cultural activity whose medium is sound and silence.", "searches": 600000},
#     {"word": "Sports", "description": "Physical activity or games governed by a set of rules or customs.", "searches": 650000},
#     {"word": "Fashion", "description": "Popular styles or practices, especially in clothing, accessories, or behavior.", "searches": 700000},
#     {"word": "Travel", "description": "Movement of people between distant geographical locations.", "searches": 750000},
#     {"word": "Entertainment", "description": "Activities that provide amusement or enjoyment.", "searches": 650000},
#     {"word": "Nature", "description": "The phenomena of the physical world collectively.", "searches": 300000},
#     {"word": "Books", "description": "Written or printed works consisting of pages bound together.", "searches": 400000},
#     {"word": "Movies", "description": "Form of visual communication that uses moving pictures to tell stories.", "searches": 600000},
#     {"word": "Pets", "description": "Domesticated animals kept for companionship or pleasure.", "searches": 500000},
#     {"word": "Paris", "description": "Capital city of France known for its art, culture, and landmarks like the Eiffel Tower.", "searches": 800000},
#     {"word": "New York City", "description": "Major city in the United States renowned for finance, art, and iconic sites such as Times Square.", "searches": 750000},
#     {"word": "Tokyo", "description": "Capital city of Japan known for its modern technology, fashion, and traditional culture.", "searches": 700000},
#     {"word": "London", "description": "Capital city of England recognized for its history, architecture, and diverse cultural scene.", "searches": 650000},
#     {"word": "Rome", "description": "Capital city of Italy famous for its ancient history, art, and landmarks like the Colosseum.", "searches": 600000},
#     {"word": "Sydney", "description": "Major city in Australia known for its harbor, opera house, and beautiful beaches.", "searches": 650000},
#     {"word": "Rio de Janeiro", "description": "City in Brazil famous for its vibrant carnival, beaches, and iconic Christ the Redeemer statue.", "searches": 550000},
#     {"word": "Cairo", "description": "Capital city of Egypt renowned for its ancient history, pyramids, and Sphinx.", "searches": 500000},
#     {"word": "Moscow", "description": "Capital city of Russia known for its historic Red Square, Kremlin, and rich cultural heritage.", "searches": 550000},
#     {"word": "Dubai", "description": "City in the United Arab Emirates recognized for its modern architecture, luxury shopping, and vibrant nightlife.", "searches": 600000},
#     {"word": "Beijing", "description": "Capital city of China famous for its historical sites, including the Great Wall and Forbidden City.", "searches": 700000},
#     {"word": "Cape Town", "description": "City in South Africa known for its stunning landscapes, diverse culture, and Table Mountain.", "searches": 450000},
#     {"word": "Venice", "description": "City in Italy renowned for its canals, historic architecture, and art.", "searches": 500000},
#     {"word": "Barcelona", "description": "City in Spain celebrated for its architecture, art, and rich cultural heritage.", "searches": 550000},
#     {"word": "Machu Picchu", "description": "Ancient Incan city in Peru, known for its archaeological significance and scenic beauty.", "searches": 300000},
#     {"word": "Agra", "description": "City in India housing the iconic Taj Mahal, a UNESCO World Heritage site.", "searches": 350000},
#     {"word": "Beyoncé", "description": "Singer, songwriter, and actress known for her powerful vocals and influential music career.", "searches": 700000},
#     {"word": "Dwayne Johnson", "description": "Actor and former professional wrestler, also known as 'The Rock', prominent in action films.", "searches": 650000},
#     {"word": "Taylor Swift", "description": "Singer-songwriter known for her narrative songwriting and success in the pop and country music genres.", "searches": 700000},
#     {"word": "Leonardo DiCaprio", "description": "Award-winning actor known for his roles in various critically acclaimed films.", "searches": 450000},
#     {"word": "Rihanna", "description": "Singer, actress, and entrepreneur recognized for her music, fashion, and cosmetics line.", "searches": 650000},
#     {"word": "Chris Hemsworth", "description": "Actor known for portraying Thor in the Marvel Cinematic Universe.", "searches": 400000},
#     {"word": "Adele", "description": "Singer-songwriter known for her soulful voice and emotionally resonant songs.", "searches": 500000},
#     {"word": "Will Smith", "description": "Actor, producer, and rapper known for his roles in blockbuster movies and TV shows.", "searches": 550000},
#     {"word": "Emma Watson", "description": "Actress and activist known for her role as Hermione Granger in the Harry Potter film series.", "searches": 450000},
#     {"word": "Kanye West", "description": "Rapper, producer, and fashion designer known for his music and controversial public persona.", "searches": 600000},
#     {"word": "Angelina Jolie", "description": "Actress, filmmaker, and humanitarian known for her work in both blockbusters and humanitarian efforts.", "searches": 550000},
#     {"word": "Tom Hanks", "description": "Academy Award-winning actor known for his versatile roles in a wide range of films.", "searches": 500000},
#     {"word": "Jennifer Lopez", "description": "Singer, actress, and dancer known for her music, acting, and business ventures.", "searches": 600000},
#     {"word": "Brad Pitt", "description": "Actor and producer known for his roles in various critically acclaimed films.", "searches": 550000},
#     {"word": "Oprah Winfrey", "description": "Media executive, talk show host, and philanthropist known for 'The Oprah Winfrey Show' and her influential career.", "searches": 450000},
# ]
# 