GAME_DATA = [
    {"word": "Technology", "description": "The study and development of tools, machines, and systems.", "searches": 550000},
    {"word": "Science", "description": "The systematic study of the structure and behavior of the physical and natural world.", "searches": 500000},
    {"word": "Art", "description": "Expression or application of human creative skill and imagination.", "searches": 450000},
    {"word": "Health", "description": "State of being free from illness or injury; overall well-being.", "searches": 400000},
    {"word": "Education", "description": "The process of receiving or giving systematic instruction.", "searches": 400000},
    {"word": "History", "description": "Study of past events, particularly in human affairs.", "searches": 350000},
    {"word": "Environment", "description": "The surroundings or conditions in which a person, animal, or plant lives.", "searches": 350000},
    {"word": "Culture", "description": "The customs, arts, social institutions, and achievements of a particular nation or people.", "searches": 400000},
    {"word": "Food", "description": "Any nutritious substance that people or animals eat or drink.", "searches": 600000},
    {"word": "Business", "description": "Activities involved in the trade of goods or services.", "searches": 550000},
    {"word": "Politics", "description": "Activities associated with governance and decision-making within a group or organization.", "searches": 450000},
    {"word": "Music", "description": "Art form and cultural activity whose medium is sound and silence.", "searches": 600000},
    {"word": "Sports", "description": "Physical activity or games governed by a set of rules or customs.", "searches": 650000},
    {"word": "Fashion", "description": "Popular styles or practices, especially in clothing, accessories, or behavior.", "searches": 700000},
    {"word": "Travel", "description": "Movement of people between distant geographical locations.", "searches": 750000},
    {"word": "Entertainment", "description": "Activities that provide amusement or enjoyment.", "searches": 650000},
    {"word": "Nature", "description": "The phenomena of the physical world collectively.", "searches": 300000},
    {"word": "Books", "description": "Written or printed works consisting of pages bound together.", "searches": 400000},
    {"word": "Movies", "description": "Form of visual communication that uses moving pictures to tell stories.", "searches": 600000},
    {"word": "Pets", "description": "Domesticated animals kept for companionship or pleasure.", "searches": 500000},
    {"word": "Paris", "description": "Capital city of France known for its art, culture, and landmarks like the Eiffel Tower.", "searches": 800000},
    {"word": "New York City", "description": "Major city in the United States renowned for finance, art, and iconic sites such as Times Square.", "searches": 750000},
    {"word": "Tokyo", "description": "Capital city of Japan known for its modern technology, fashion, and traditional culture.", "searches": 700000},
    {"word": "London", "description": "Capital city of England recognized for its history, architecture, and diverse cultural scene.", "searches": 650000},
    {"word": "Rome", "description": "Capital city of Italy famous for its ancient history, art, and landmarks like the Colosseum.", "searches": 600000},
    {"word": "Sydney", "description": "Major city in Australia known for its harbor, opera house, and beautiful beaches.", "searches": 650000},
    {"word": "Rio de Janeiro", "description": "City in Brazil famous for its vibrant carnival, beaches, and iconic Christ the Redeemer statue.", "searches": 550000},
    {"word": "Cairo", "description": "Capital city of Egypt renowned for its ancient history, pyramids, and Sphinx.", "searches": 500000},
    {"word": "Moscow", "description": "Capital city of Russia known for its historic Red Square, Kremlin, and rich cultural heritage.", "searches": 550000},
    {"word": "Dubai", "description": "City in the United Arab Emirates recognized for its modern architecture, luxury shopping, and vibrant nightlife.", "searches": 600000},
    {"word": "Beijing", "description": "Capital city of China famous for its historical sites, including the Great Wall and Forbidden City.", "searches": 700000},
    {"word": "Cape Town", "description": "City in South Africa known for its stunning landscapes, diverse culture, and Table Mountain.", "searches": 450000},
    {"word": "Venice", "description": "City in Italy renowned for its canals, historic architecture, and art.", "searches": 500000},
    {"word": "Barcelona", "description": "City in Spain celebrated for its architecture, art, and rich cultural heritage.", "searches": 550000},
    {"word": "Machu Picchu", "description": "Ancient Incan city in Peru, known for its archaeological significance and scenic beauty.", "searches": 300000},
    {"word": "Agra", "description": "City in India housing the iconic Taj Mahal, a UNESCO World Heritage site.", "searches": 350000},
    {"word": "Beyoncé", "description": "Singer, songwriter, and actress known for her powerful vocals and influential music career.", "searches": 700000},
    {"word": "Dwayne Johnson", "description": "Actor and former professional wrestler, also known as 'The Rock', prominent in action films.", "searches": 650000},
    {"word": "Taylor Swift", "description": "Singer-songwriter known for her narrative songwriting and success in the pop and country music genres.", "searches": 700000},
    {"word": "Leonardo DiCaprio", "description": "Award-winning actor known for his roles in various critically acclaimed films.", "searches": 450000},
    {"word": "Rihanna", "description": "Singer, actress, and entrepreneur recognized for her music, fashion, and cosmetics line.", "searches": 650000},
    {"word": "Chris Hemsworth", "description": "Actor known for portraying Thor in the Marvel Cinematic Universe.", "searches": 400000},
    {"word": "Adele", "description": "Singer-songwriter known for her soulful voice and emotionally resonant songs.", "searches": 500000},
    {"word": "Will Smith", "description": "Actor, producer, and rapper known for his roles in blockbuster movies and TV shows.", "searches": 550000},
    {"word": "Emma Watson", "description": "Actress and activist known for her role as Hermione Granger in the Harry Potter film series.", "searches": 450000},
    {"word": "Kanye West", "description": "Rapper, producer, and fashion designer known for his music and controversial public persona.", "searches": 600000},
    {"word": "Angelina Jolie", "description": "Actress, filmmaker, and humanitarian known for her work in both blockbusters and humanitarian efforts.", "searches": 550000},
    {"word": "Tom Hanks", "description": "Academy Award-winning actor known for his versatile roles in a wide range of films.", "searches": 500000},
    {"word": "Jennifer Lopez", "description": "Singer, actress, and dancer known for her music, acting, and business ventures.", "searches": 600000},
    {"word": "Brad Pitt", "description": "Actor and producer known for his roles in various critically acclaimed films.", "searches": 550000},
    {"word": "Oprah Winfrey", "description": "Media executive, talk show host, and philanthropist known for 'The Oprah Winfrey Show' and her influential career.", "searches": 450000},
]
